### ISSUE TITLE
Delete images which are replaced on edit

### ISSUE THREAD

**Issue by tgoeminne** [FriendsOfCake/cakephp-upload#527] opened 2020-01-15 04:29 UTC
I was looking at the plugin and noticed that 'keepFilesOnDelete' => false, only works when you actually delete the file.
Can you make it so that when there is only one upload attached to a record; that when you edit the field that the old file gets deleted?

eg as in the following

$this->addBehavior('Josegonzalez/Upload.Upload', [
             'logo' => [
                'path' => 'webroot{DS}files{DS}Articles{DS}logos{DS}',
                'keepFilesOnDelete' => false,
            ]

When you edit the logo field, the old logo does not get removed it seems.

**Comment by tgoeminne** [comment] 2020-01-16 06:43
It's also like when you edit an attachment record so that the attachment becomes a new file. Then it should be considered a delete of the old file? Maybe have a setting like "keepFilesOnEdit" and check if the value isDirty when existing records get updated?

**Comment by davidyell** [comment] 2020-01-16 15:24
This feels like something you could implement into your own Writer class.

**Comment by saeideng** [comment] 2022-02-09 17:22
duplicate of #493

**Closed** 2022-02-09 17:22 UTC
Labels: feature, request
